export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL';
export const AUTH_CHANGE_NIKNAME = 'AUTH_CHANGE_NIKNAME';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';

export const AUTH_SET_EMAIL_ERROR = 'AUTH_SET_EMAIL_ERROR';
export const AUTH_SET_NIKNAME_ERROR = 'AUTH_SET_NIKNAME_ERROR';
export const AUTH_SET_PASSWORD_ERROR = 'AUTH_SET_PASSWORD_ERROR';
export const AUTH_CHANGED_NIKNAME_STATE = 'AUTH_CHANGED_NIKNAME_STATE';
export const AUTH_CHANGED_PASSWORD_STATE = 'AUTH_CHANGED_PASSWORD_STATE';
export const AUTH_CHANGED_EMAIL_STATE = 'AUTH_CHANGED_EMAIL_STATE';
export const AUTH_API_SUCCESS = 'AUTH_API_SUCCESS';
export const AUTH_API_ERROR = 'AUTH_API_ERROR';
export const AUTH_RESET_FORM = 'AUTH_RESET_FORM';