export const GAME_SET_PLAYER = 'GAME_SET_PLAYER';
export const GAME_SET_GAME = 'GAME_SET_GAME';
export const GAME_SET_CURRENT_ROUND = 'GAME_SET_CURRENT_ROUND';
export const GAME_SET_CHAT_MESSAGE = 'GAME_SET_CHAT_MESSAGE';