export const CREATE_ROOM_CHANGE_NAME = 'CREATE_ROOM_CHANGE_NAME';
export const CREATE_ROOM_SET_NAME_ERROR = 'CREATE_ROOM_SET_NAME_ERROR';
export const CREATE_ROOM_CHANGED_NAME_STATE = 'CREATE_ROOM_CHANGED_NAME_STATE';
export const CREATE_ROOM_API_ERROR = 'CREATE_ROOM_API_ERROR';
export const CREATE_ROOM_RESET_FORM = 'CREATE_ROOM_RESET_FORM';