export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL';
export const AUTH_CHANGE_NIKNAME = 'AUTH_CHANGE_NIKNAME';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';
export const AUTH_SET_ERROR = 'AUTH_SET_ERROR';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const AUTH_RESET_FORM = 'AUTH_RESET_FORM';